# Generated by Django 3.2.13 on 2022-06-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=10)),
                ('codigo', models.IntegerField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=10)),
                ('serie', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.recurso')),
            ],
        ),
    ]
